project_id = "oprscgxsfldzydbrbioz"

[functions.analyze-creative]
verify_jwt = true

[functions.transform-creative]
verify_jwt = true

[functions.gcs-upload-file]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.meta-ads-direct]
verify_jwt = true

[functions.meta-oauth-callback]
verify_jwt = false

[functions.meta-oauth-init]
verify_jwt = true

[functions.meta-refresh-token]
verify_jwt = true

[functions.metrics-direct]
verify_jwt = true

[functions.scrape-competitor-ads]
verify_jwt = true

[functions.poll-competitor-search]
verify_jwt = true

[functions.upload-to-storage]
verify_jwt = true

[functions.refresh-competitor-ads-cache]
verify_jwt = false

[functions.migrate-to-gcs]
verify_jwt = true

[functions.send-mention-email]
verify_jwt = false

[functions.support-auto-reply]
verify_jwt = false

[functions.validate-email]
verify_jwt = false

[functions.check-video-status]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.analyze-group]
verify_jwt = true

[functions.finalize-competitor-search]
verify_jwt = true

[functions.generate-briefing]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.suggest-taxonomy]
verify_jwt = true

[functions.sync-meta-data]
verify_jwt = true

[functions.figma-oauth-init]
verify_jwt = true

[functions.figma-oauth-callback]
verify_jwt = false

[functions.figma-api]
verify_jwt = true
